services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      retries: 5

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - 127.0.0.1:1080:1080
      - 127.0.0.1:1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
