services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      retries: 5

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - 127.0.0.1:1080:1080
      - 127.0.0.1:1025:1025
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:0.0.1-SNAPSHOT
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
      - TOKEN_KEY=${TOKEN_KEY}
      - DB_URL=${DB_URL}
      - JAR_VERSION=${JAR_VERSION}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}

    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres



networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
